"""add users table

Revision ID: 2cf63d302668
Revises: 0001_initial
Create Date: 2026-06-14 13:54:35.262845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf63d302668'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_clientes_ativo'))

    with op.batch_alter_table('itens_orcamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_orcamento_orcamento_id'))
        batch_op.drop_constraint(batch_op.f('fk_itens_orcamento_orcamento_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_itens_orcamento_categoria_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_itens_orcamento_produto_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orcamentos', ['orcamento_id'], ['id'])
        batch_op.create_foreign_key(None, 'categorias_produtos', ['categoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'produtos', ['produto_id'], ['id'])

    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_orcamentos_status'))
        batch_op.drop_constraint(batch_op.f('fk_orcamentos_cliente_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_produtos_ativo'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_unidade_medida_id'))
        batch_op.drop_constraint(batch_op.f('fk_produtos_categoria_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_produtos_unidade_medida_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_medidas', ['unidade_medida_id'], ['id'])
        batch_op.create_foreign_key(None, 'categorias_produtos', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_produtos_unidade_medida_id'), 'unidades_medidas', ['unidade_medida_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_produtos_categoria_id'), 'categorias_produtos', ['categoria_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('ix_produtos_unidade_medida_id'), ['unidade_medida_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_ativo'), ['ativo'], unique=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orcamentos_cliente_id'), 'clientes', ['cliente_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('ix_orcamentos_status'), ['status'], unique=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('itens_orcamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_itens_orcamento_produto_id'), 'produtos', ['produto_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_itens_orcamento_categoria_id'), 'categorias_produtos', ['categoria_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_itens_orcamento_orcamento_id'), 'orcamentos', ['orcamento_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_itens_orcamento_orcamento_id'), ['orcamento_id'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_ativo'), ['ativo'], unique=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    op.drop_table('users')
    # ### end Alembic commands ###
