"""add servico, pagamento, parcela e gasto

Revision ID: 32dc0403a59d
Revises: 2cf63d302668
Create Date: 2026-06-14 17:36:14.218618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32dc0403a59d'
down_revision = '2cf63d302668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('pix', 'cartao_credito', 'cartao_debito', 'boleto', 'dinheiro', 'transferencia', name='forma_pagamento_gasto'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas_gasto',
    sa.Column('gasto_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'pago', 'atrasado', name='status_parcela_gasto'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcelas_gasto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_gasto_gasto_id'), ['gasto_id'], unique=False)

    op.create_table('servicos',
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('agendado', 'em_andamento', 'concluido', 'cancelado', name='status_servico'), nullable=False),
    sa.Column('data_execucao', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicos_orcamento_id'), ['orcamento_id'], unique=True)

    op.create_table('pagamentos',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('pix', 'cartao_credito', 'cartao_debito', 'boleto', 'dinheiro', 'transferencia', name='forma_pagamento'), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_servico_id'), ['servico_id'], unique=True)

    op.create_table('parcelas_pagamento',
    sa.Column('pagamento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'pago', 'atrasado', name='status_parcela'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcelas_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_pagamento_pagamento_id'), ['pagamento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcelas_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_pagamento_pagamento_id'))

    op.drop_table('parcelas_pagamento')
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_servico_id'))

    op.drop_table('pagamentos')
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicos_orcamento_id'))

    op.drop_table('servicos')
    with op.batch_alter_table('parcelas_gasto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_gasto_gasto_id'))

    op.drop_table('parcelas_gasto')
    op.drop_table('gastos')
    # ### end Alembic commands ###
