"""add unidade_medida_id to gastos

Revision ID: 78d76963e0c5
Revises: 32dc0403a59d
Create Date: 2026-06-14 17:53:50.667523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d76963e0c5'
down_revision = '32dc0403a59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_gastos_unidade_medida_id'), ['unidade_medida_id'], unique=False)
        batch_op.create_foreign_key(None, 'unidades_medidas', ['unidade_medida_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_gastos_unidade_medida_id'))
        batch_op.drop_column('unidade_medida_id')

    # ### end Alembic commands ###
